[[providers]]
name = "history"
kind = "csv"
resource = "history.csv"

[[providers]]
name = "programming"
kind = "text"
resource = "programming.txt"

[[providers]]
name = "computing"
kind = "text"
resource = "computing.txt"

[[providers]]
name = "rust-info"
kind = "new"
resource = ""

[[providers]]
name = "events-db"
kind = "sqlite"
resource = "events.db"

