[[providers]]
name = "history"
kind = "csv"
resource = "history.csv"

[[providers]]
name = "programming"
kind = "text"
resource = "programming.txt"

[[providers]]
name = "computing"
kind = "new"
resource = "computing.txt"